### ISSUE TITLE
Incompatibility with rclpy.time from Jazzy

### ISSUE THREAD

**Issue by wentasah** [AIT-Assistive-Autonomous-Systems/ros2bag_tools#38]
In Jazzy, `ros2 bag` prints warnings like this:
```
Failed to load entry point 'cut': cannot import name 'CONVERSION_CONSTANT' from 'rclpy.time'
```
This seems to be caused by https://github.com/ros2/rclpy/pull/1237, which removes `CONVERSION_CONSTANT`.

**Comment by devrite** [comment]
Yes, we are not yet migrated to the API changes of rolling in jazzy. See #31 and #34. If you want to use it I suggest sticking with humble or iron for now when working with bags. I will close this issue as I would like all work and the way we handle time relevant changes in #31.

I started working on these but due to my work and since it took time until some other changes where finalized  upstream, I could not continue and I will probably not be able to in the next 2-4 weeks. So PR's are also welcome.
